### ISSUE TITLE
[0.5] (100분 해커톤) 디코 메신저 공지 봇 테스트 개발

### ISSUE THREAD

**Issue by seokjeon** [is119/TimeBank#13]
이 [문서](https://docs.google.com/document/d/1BPh_VsUK-W_Bn3mTB4-ypzki5jKePis52D51vD5k83c/edit?usp=sharing)에 아래 내용 적기
- [x] 필요 기능 정의
- [x] 필요 리소스 정의
- [ ] 결과물 제작

**Comment by CMS1108** [comment]
@CMS1108 test

**Comment by CMS1108** [comment]
@CMS1108 test1

**Comment by CMS1108** [comment]
@CMS1108 test2

**Comment by CMS1108** [comment]
@CMS1108 test2

**Comment by CMS1108** [comment]
asdf

**Comment by CMS1108** [comment]
@seokjeon 문서 작성 완료

**Comment by seokjeon** [comment]
@CMS1108 굿 결과물 제작 빼놓고 체크하고,

**Comment by CMS1108** [comment]
@seokjeon 이거도 좀 날먹이라서 0.5로 처리하면 될듯ㅋㅋ

**Comment by seokjeon** [comment]
@CMS1108 니맘대로 ㅋㅋ
