### ISSUE TITLE
[0.5] (100분 해커톤) 카톡 메신저 공지 봇 테스트 개발

### ISSUE THREAD

**Issue by seokjeon** [is119/TimeBank#14]
이 [문서](https://docs.google.com/document/d/1BPh_VsUK-W_Bn3mTB4-ypzki5jKePis52D51vD5k83c/edit?usp=sharing)에 아래 내용 적기
- [x] 필요 기능 정의
- [x] 필요 리소스 정의
- [ ] 결과물 제작

**Comment by seokjeon** [comment]
@CMS1108 카톡은 Github이랑 연동하려면 한세월이라 1시간 반안에 절대 개발 못하겠드라 ㅋㅋㅋ
한 0.5정도로 쳐주라

**Comment by CMS1108** [comment]
@seokjeon  ㅋㅋ ㅇㅋ
