### ISSUE TITLE
[2] 동계 스터디 주제 선정 및 팀 구성

### ISSUE THREAD

**Issue by Pa-Ka** [is119/TimeBank#5]
- [x] 단체 톡방 생성
- [x] 스터디 책 정하기
- [x] 활동 인원 취합
- [x] 입금 확인
- [x] 스터디 보증금 관리용 스프레드시트 생성  

입금 확인 및 활동 인원에 대한 문의 사항은 회장한테 연락주면 바로 확인 가능함.

**Comment by seokjeon** [comment]
[관리용 스프레드 시트](https://docs.google.com/spreadsheets/d/1i-_-Qy59nJtH8oFVruxVtX18cRhVFTSxyt4xCdBHr_o/edit?usp=sharing)

솔직히 이건 2시간 반은 줘야한다.
@Pa-Ka 인정해줘요. 글고 더 필요한거 없죠?
@CMS1108  그리고 나서 이거 정산 좀

**Comment by Pa-Ka** [comment]
ㅇㅈ 짜게준 감이 있지.
